[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.6.3", features = ["web", "router"] }
reqwest = { version = "0.12", default-features = false, features = ["json"] }
wasm-logger = "0.2"
uuid = { version = "1.11", default-features = false, features = ["v4", "serde", "js"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
futures-util = "0.3"
futures-channel = "0.3"
tracing = "0.1"
