[application]
name = "aazan"
default_platform = "web"

[web.app]
title = "Aazan - Learn by Teaching"
base_path = "/"

[web.watcher]
watch_path = ["src/frontend", "assets"]
reload_html = true
index_on_404 = true

[web.resource]
style = []

[[web.proxy]]
backend = "http://localhost:3000/api"

[web.resource.dev]
